[package]
name = "rst"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.11.1"
libc = "0.2.186"
winit = { version = "0.30.13", features = ["wayland-dlopen"], default-features = false }
glutin = { version = "0.32.3", features = ["wayland"], default-features = false }
glutin-winit = {version = "0.5.0", features = ["wayland", "egl"], default-features = false }
glow = "0.17.0"
fontconfig = { version = "0.10.0", features = ["dlopen"] }
yeslogic-fontconfig-sys = { version = "6.0.0", features = ["dlopen"] }
freetype-rs = "0.38.0"
rustybuzz = "0.20.1"
bytemuck = "1.25.0"
unicode-width = "0.2.2"
